version: 2.6.{build}
image: Visual Studio 2017


environment:
  matrix:
  - PlatformToolset: v141

platform:
    - x64
    - Win32
    - arm64

configuration:
    - Release
    - Debug

install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="x64" set platform_input=x64

    - if "%platform%"=="Win32" set archi=x86
    - if "%platform%"=="Win32" set platform_input=Win32

    - if "%platform%"=="arm64" set archi=amd64_arm64
    - if "%platform%"=="arm64" set platform_input=arm64

    - if "%PlatformToolset%"=="v141" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%
    - if "%PlatformToolset%"=="v142" call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%

build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"\vs.proj
    - msbuild mimeTools.vcxproj /m /p:configuration="%configuration%" /p:platform="%platform_input%" /p:PlatformToolset="%PlatformToolset%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - ps: >-
        $mimeToolsFileName = "mimeTools.$env:PLATFORM_INPUT.$env:CONFIGURATION.$env:PLATFORMTOOLSET.dll"

        if ($env:PLATFORM_INPUT -eq "x64" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "bin64\mimeTools.dll" -FileName "$mimeToolsFileName"
        }

        if ($env:PLATFORM_INPUT -eq "x64" -and $env:CONFIGURATION -eq "Debug") {
            Push-AppveyorArtifact "vs.proj\x64\Debug\mimeTools.dll" -FileName "$mimeToolsFileName"
        }

        if ($env:PLATFORM_INPUT -eq "Win32" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "bin\mimeTools.dll" -FileName "$mimeToolsFileName"
        }

        if ($env:PLATFORM_INPUT -eq "Win32" -and $env:CONFIGURATION -eq "Debug") {
            Push-AppveyorArtifact "vs.proj\Debug\mimeTools.dll" -FileName "$mimeToolsFileName"
        }

        if ($env:PLATFORM_INPUT -eq "arm64" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "arm64\mimeTools.dll" -FileName "$mimeToolsFileName"
        }

        if ($env:PLATFORM_INPUT -eq "arm64" -and $env:CONFIGURATION -eq "Debug") {
            Push-AppveyorArtifact "vs.proj\ARM64\Debug\mimeTools.dll" -FileName "$mimeToolsFileName"
        }

